// Auto-generated by scripts/split_napi_v8.py.
// Per-category extern "C" entry points; helpers in internals.cc.

#include <algorithm>
#include <climits>
#include <cmath>
#define NAPI_EXPERIMENTAL
#include "js_native_api_v8.h"
#include "js_native_api_v8_impl.h"
#include "napi/js_native_api.h"
#include "napi/node_api.h"

#define CHECK_MAYBE_NOTHING(env, maybe, status) RETURN_STATUS_IF_FALSE((env), !((maybe).IsNothing()), (status))

#define CHECK_MAYBE_NOTHING_WITH_PREAMBLE(env, maybe, status)                                                          \
    RETURN_STATUS_IF_FALSE_WITH_PREAMBLE((env), !((maybe).IsNothing()), (status))

#define CHECK_TO_NUMBER(env, context, result, src)                                                                     \
    CHECK_TO_TYPE((env), Number, (context), (result), (src), napi_number_expected)

#define CHECK_NEW_FROM_UTF8_LEN(env, result, str, len)                                                                 \
    do {                                                                                                               \
        static_assert(static_cast<int>(NAPI_AUTO_LENGTH) == -1, "Casting NAPI_AUTO_LENGTH to int must result in -1");  \
        RETURN_STATUS_IF_FALSE((env), (len == NAPI_AUTO_LENGTH) || len <= INT_MAX, napi_invalid_arg);                  \
        RETURN_STATUS_IF_FALSE((env), (str) != nullptr, napi_invalid_arg);                                             \
        auto str_maybe = v8::String::NewFromUtf8((env)->isolate, (str), v8::NewStringType::kInternalized,              \
                                                 static_cast<int>(len));                                               \
        CHECK_MAYBE_EMPTY((env), str_maybe, napi_generic_failure);                                                     \
        (result) = str_maybe.ToLocalChecked();                                                                         \
    } while (0)

#define CHECK_NEW_FROM_UTF8(env, result, str) CHECK_NEW_FROM_UTF8_LEN((env), (result), (str), NAPI_AUTO_LENGTH)

#define CREATE_TYPED_ARRAY(env, type, size_of_element, buffer, byte_offset, length, out)                               \
    do {                                                                                                               \
        if ((size_of_element) > 1) {                                                                                   \
            THROW_RANGE_ERROR_IF_FALSE((env), (byte_offset) % (size_of_element) == 0,                                  \
                                       "ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT",                                        \
                                       "start offset of " #type " should be a multiple of " #size_of_element);         \
        }                                                                                                              \
        THROW_RANGE_ERROR_IF_FALSE((env), (length) * (size_of_element) + (byte_offset) <= buffer->ByteLength(),        \
                                   "ERR_NAPI_INVALID_TYPEDARRAY_LENGTH", "Invalid typed array length");                \
        (out) = v8::type::New((buffer), (byte_offset), (length));                                                      \
    } while (0)

napi_status NAPI_CDECL napi_open_handle_scope(napi_env env, napi_handle_scope *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsHandleScopeFromV8HandleScope(new v8impl::HandleScopeWrapper(env->isolate));
    env->open_handle_scopes++;
    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_close_handle_scope(napi_env env, napi_handle_scope scope) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, scope);
    if (env->open_handle_scopes == 0) {
        return napi_handle_scope_mismatch;
    }

    env->open_handle_scopes--;
    delete v8impl::V8HandleScopeFromJsHandleScope(scope);
    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_open_escapable_handle_scope(napi_env env, napi_escapable_handle_scope *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsEscapableHandleScopeFromV8EscapableHandleScope(
            new v8impl::EscapableHandleScopeWrapper(env->isolate));
    env->open_handle_scopes++;
    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_close_escapable_handle_scope(napi_env env, napi_escapable_handle_scope scope) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, scope);
    if (env->open_handle_scopes == 0) {
        return napi_handle_scope_mismatch;
    }

    delete v8impl::V8EscapableHandleScopeFromJsEscapableHandleScope(scope);
    env->open_handle_scopes--;
    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_escape_handle(napi_env env, napi_escapable_handle_scope scope, napi_value escapee,
                                          napi_value *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, scope);
    CHECK_ARG(env, escapee);
    CHECK_ARG(env, result);

    v8impl::EscapableHandleScopeWrapper *s = v8impl::V8EscapableHandleScopeFromJsEscapableHandleScope(scope);
    if (!s->escape_called()) {
        *result = v8impl::JsValueFromV8LocalValue(s->Escape(v8impl::V8LocalValueFromJsValue(escapee)));
        return napi_clear_last_error(env);
    }
    return napi_set_last_error(env, napi_escape_called_twice);
}
