// Auto-generated by scripts/split_napi_v8.py.
// Per-category extern "C" entry points; helpers in internals.cc.

#include <algorithm>
#include <climits>
#include <cmath>
#define NAPI_EXPERIMENTAL
#include "js_native_api_v8.h"
#include "js_native_api_v8_impl.h"
#include "napi/js_native_api.h"
#include "napi/node_api.h"

#define CHECK_MAYBE_NOTHING(env, maybe, status) RETURN_STATUS_IF_FALSE((env), !((maybe).IsNothing()), (status))

#define CHECK_MAYBE_NOTHING_WITH_PREAMBLE(env, maybe, status)                                                          \
    RETURN_STATUS_IF_FALSE_WITH_PREAMBLE((env), !((maybe).IsNothing()), (status))

#define CHECK_TO_NUMBER(env, context, result, src)                                                                     \
    CHECK_TO_TYPE((env), Number, (context), (result), (src), napi_number_expected)

#define CHECK_NEW_FROM_UTF8_LEN(env, result, str, len)                                                                 \
    do {                                                                                                               \
        static_assert(static_cast<int>(NAPI_AUTO_LENGTH) == -1, "Casting NAPI_AUTO_LENGTH to int must result in -1");  \
        RETURN_STATUS_IF_FALSE((env), (len == NAPI_AUTO_LENGTH) || len <= INT_MAX, napi_invalid_arg);                  \
        RETURN_STATUS_IF_FALSE((env), (str) != nullptr, napi_invalid_arg);                                             \
        auto str_maybe = v8::String::NewFromUtf8((env)->isolate, (str), v8::NewStringType::kInternalized,              \
                                                 static_cast<int>(len));                                               \
        CHECK_MAYBE_EMPTY((env), str_maybe, napi_generic_failure);                                                     \
        (result) = str_maybe.ToLocalChecked();                                                                         \
    } while (0)

#define CHECK_NEW_FROM_UTF8(env, result, str) CHECK_NEW_FROM_UTF8_LEN((env), (result), (str), NAPI_AUTO_LENGTH)

#define CREATE_TYPED_ARRAY(env, type, size_of_element, buffer, byte_offset, length, out)                               \
    do {                                                                                                               \
        if ((size_of_element) > 1) {                                                                                   \
            THROW_RANGE_ERROR_IF_FALSE((env), (byte_offset) % (size_of_element) == 0,                                  \
                                       "ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT",                                        \
                                       "start offset of " #type " should be a multiple of " #size_of_element);         \
        }                                                                                                              \
        THROW_RANGE_ERROR_IF_FALSE((env), (length) * (size_of_element) + (byte_offset) <= buffer->ByteLength(),        \
                                   "ERR_NAPI_INVALID_TYPEDARRAY_LENGTH", "Invalid typed array length");                \
        (out) = v8::type::New((buffer), (byte_offset), (length));                                                      \
    } while (0)

napi_status NAPI_CDECL napi_strict_equals(napi_env env, napi_value lhs, napi_value rhs, bool *result) {
    NAPI_PREAMBLE(env);
    CHECK_ARG(env, lhs);
    CHECK_ARG(env, rhs);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> a = v8impl::V8LocalValueFromJsValue(lhs);
    v8::Local<v8::Value> b = v8impl::V8LocalValueFromJsValue(rhs);

    *result = a->StrictEquals(b);
    return GET_RETURN_STATUS(env);
}


napi_status NAPI_CDECL napi_create_double(napi_env env, double value, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(v8::Number::New(env->isolate, value));

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_create_int32(napi_env env, int32_t value, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(v8::Integer::New(env->isolate, value));

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_create_uint32(napi_env env, uint32_t value, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(v8::Integer::NewFromUnsigned(env->isolate, value));

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_create_int64(napi_env env, int64_t value, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(v8::Number::New(env->isolate, static_cast<double>(value)));

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_boolean(napi_env env, bool value, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    v8::Isolate *isolate = env->isolate;

    if (value) {
        *result = v8impl::JsValueFromV8LocalValue(v8::True(isolate));
    } else {
        *result = v8impl::JsValueFromV8LocalValue(v8::False(isolate));
    }

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_typeof(napi_env env, napi_value value, napi_valuetype *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> v = v8impl::V8LocalValueFromJsValue(value);

    if (v->IsNumber()) {
        *result = napi_number;
    } else if (v->IsBigInt()) {
        *result = napi_bigint;
    } else if (v->IsString()) {
        *result = napi_string;
    } else if (v->IsFunction()) {
        // This test has to come before IsObject because IsFunction
        // implies IsObject
        *result = napi_function;
    } else if (v->IsExternal()) {
        // This test has to come before IsObject because IsExternal
        // implies IsObject
        *result = napi_external;
    } else if (v->IsObject()) {
        *result = napi_object;
    } else if (v->IsBoolean()) {
        *result = napi_boolean;
    } else if (v->IsUndefined()) {
        *result = napi_undefined;
    } else if (v->IsSymbol()) {
        *result = napi_symbol;
    } else if (v->IsNull()) {
        *result = napi_null;
    } else {
        // Should not get here unless V8 has added some new kind of value.
        return napi_set_last_error(env, napi_invalid_arg);
    }

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_undefined(napi_env env, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(v8::Undefined(env->isolate));

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_null(napi_env env, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(v8::Null(env->isolate));

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_global(napi_env env, napi_value *result) {
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, result);

    *result = v8impl::JsValueFromV8LocalValue(env->context()->Global());

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_value_double(napi_env env, napi_value value, double *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> val = v8impl::V8LocalValueFromJsValue(value);
    RETURN_STATUS_IF_FALSE(env, val->IsNumber(), napi_number_expected);

    *result = val.As<v8::Number>()->Value();

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_value_int32(napi_env env, napi_value value, int32_t *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> val = v8impl::V8LocalValueFromJsValue(value);

    if (val->IsInt32()) {
        *result = val.As<v8::Int32>()->Value();
    } else {
        RETURN_STATUS_IF_FALSE(env, val->IsNumber(), napi_number_expected);

        // Empty context: https://github.com/nodejs/node/issues/14379
        v8::Local<v8::Context> context;
        *result = val->Int32Value(context).FromJust();
    }

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_value_uint32(napi_env env, napi_value value, uint32_t *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> val = v8impl::V8LocalValueFromJsValue(value);

    if (val->IsUint32()) {
        *result = val.As<v8::Uint32>()->Value();
    } else {
        RETURN_STATUS_IF_FALSE(env, val->IsNumber(), napi_number_expected);

        // Empty context: https://github.com/nodejs/node/issues/14379
        v8::Local<v8::Context> context;
        *result = val->Uint32Value(context).FromJust();
    }

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_value_int64(napi_env env, napi_value value, int64_t *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> val = v8impl::V8LocalValueFromJsValue(value);

    // This is still a fast path very likely to be taken.
    if (val->IsInt32()) {
        *result = val.As<v8::Int32>()->Value();
        return napi_clear_last_error(env);
    }

    RETURN_STATUS_IF_FALSE(env, val->IsNumber(), napi_number_expected);

    // v8::Value::IntegerValue() converts NaN, +Inf, and -Inf to INT64_MIN,
    // inconsistent with v8::Value::Int32Value() which converts those values to 0.
    // Special-case all non-finite values to match that behavior.
    double doubleValue = val.As<v8::Number>()->Value();
    if (std::isfinite(doubleValue)) {
        // Empty context: https://github.com/nodejs/node/issues/14379
        v8::Local<v8::Context> context;
        *result = val->IntegerValue(context).FromJust();
    } else {
        *result = 0;
    }

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_get_value_bool(napi_env env, napi_value value, bool *result) {
    // Omit NAPI_PREAMBLE and GET_RETURN_STATUS because V8 calls here cannot throw
    // JS exceptions.
    CHECK_ENV_NOT_IN_GC(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Local<v8::Value> val = v8impl::V8LocalValueFromJsValue(value);
    RETURN_STATUS_IF_FALSE(env, val->IsBoolean(), napi_boolean_expected);

    *result = val.As<v8::Boolean>()->Value();

    return napi_clear_last_error(env);
}


napi_status NAPI_CDECL napi_coerce_to_bool(napi_env env, napi_value value, napi_value *result) {
    NAPI_PREAMBLE(env);
    CHECK_ARG(env, value);
    CHECK_ARG(env, result);

    v8::Isolate *isolate = env->isolate;
    v8::Local<v8::Boolean> b = v8impl::V8LocalValueFromJsValue(value)->ToBoolean(isolate);
    *result = v8impl::JsValueFromV8LocalValue(b);
    return GET_RETURN_STATUS(env);
}

#define GEN_COERCE_FUNCTION(UpperCaseName, MixedCaseName, LowerCaseName)                                               \
    napi_status NAPI_CDECL napi_coerce_to_##LowerCaseName(napi_env env, napi_value value, napi_value *result) {        \
        NAPI_PREAMBLE(env);                                                                                            \
        CHECK_ARG(env, value);                                                                                         \
        CHECK_ARG(env, result);                                                                                        \
                                                                                                                       \
        v8::Local<v8::Context> context = env->context();                                                               \
        v8::Local<v8::MixedCaseName> str;                                                                              \
                                                                                                                       \
        CHECK_TO_##UpperCaseName(env, context, str, value);                                                            \
                                                                                                                       \
        *result = v8impl::JsValueFromV8LocalValue(str);                                                                \
        return GET_RETURN_STATUS(env);                                                                                 \
    }

GEN_COERCE_FUNCTION(NUMBER, Number, number)
GEN_COERCE_FUNCTION(OBJECT, Object, object)
GEN_COERCE_FUNCTION(STRING, String, string)

#undef GEN_COERCE_FUNCTION
