#!/usr/bin/env python3
"""Build entrypoint for napi-impl.

V8 engine path (this script's focus):
  1. Load config/v8_args.yml (+ optional v8_args.local.yml, $NAPI_GN_EXTRA_ARGS_FILE, --gn-arg).
  2. Apply constraint expansion (jitless bundle).
  3. Write args.gn into V8's out dir.
  4. Run `gn gen` and `ninja` from the V8 source tree.
  5. Copy artifacts to out/build/<engine>-<platform>-<arch>-<config>/.

CMake engine paths (hermes/jsc/quickjs): TODO M7.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    sys.stderr.write("Missing PyYAML. Install with: pip3 install pyyaml\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
THIRD_PARTY = ROOT / "third_party"
V8_DIR = THIRD_PARTY / "v8"
HERMES_DIR = THIRD_PARTY / "hermes-windows"
DEPOT_TOOLS = THIRD_PARTY / "depot_tools"


# ---------------------------------------------------------------------------
# YAML loading & merging
# ---------------------------------------------------------------------------

def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _deep_merge(dst: dict, src: dict) -> dict:
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            _deep_merge(dst[k], v)
        else:
            dst[k] = v
    return dst


def _parse_gn_value(s: str):
    sl = s.lower()
    if sl in ("true", "false"):
        return sl == "true"
    try:
        return int(s)
    except ValueError:
        pass
    return s  # treat as string


# Constraints: when key=value matches, force the listed peers.
# 注：pointer compression 不在此 bundle——它与 jitless 正交（jitless 关 JIT，pointer
# compression 只改堆内指针布局），现已全平台关闭（见 config/v8_args.yml common）。sandbox 仍强制
# 关闭：jitless 平台同样走跨 C ABI 的 user-malloc backing store，sandbox 会限制它。
JITLESS_BUNDLE = {
    "v8_enable_webassembly": False,
    "v8_enable_sandbox": False,
    "v8_enable_maglev": False,
    "v8_enable_turbofan": False,
}


def apply_constraints(args: dict) -> dict:
    if args.get("v8_jitless") is True:
        for k, v in JITLESS_BUNDLE.items():
            if k in args and args[k] != v:
                raise SystemExit(
                    f"[constraint] v8_jitless=true forces {k}={v}, "
                    f"but user set {k}={args[k]}"
                )
            args[k] = v
    return args


def compose_args(platform: str, arch: str, config: str,
                 cli_overrides: list[str]) -> dict:
    key = f"{platform}_{arch}"
    defaults = _load_yaml(ROOT / "config" / "v8_args.yml")

    args = dict(defaults.get("common", {}))
    plat_block = defaults.get("platforms", {}).get(key)
    if plat_block is None:
        raise SystemExit(f"[error] platforms.{key} not defined in v8_args.yml")
    args.update(plat_block)

    local = _load_yaml(ROOT / "config" / "v8_args.local.yml")
    _deep_merge(args, local.get("common", {}))
    _deep_merge(args, local.get("platforms", {}).get(key, {}))

    extra_path = os.environ.get("NAPI_GN_EXTRA_ARGS_FILE")
    if extra_path:
        _deep_merge(args, _load_yaml(Path(extra_path)))

    for kv in cli_overrides:
        if "=" not in kv:
            raise SystemExit(f"[error] --gn-arg expects key=value, got: {kv}")
        k, v = kv.split("=", 1)
        args[k.strip()] = _parse_gn_value(v.strip())

    if config == "debug":
        # common 的 symbol_level=0 是 release 减包默认(A1)；debug 覆盖回完整符号。
        # 直接赋值(非 setdefault)，因 common 已把 symbol_level 设为 release 默认 0。
        args["is_debug"] = True
        args["symbol_level"] = 2
    elif config == "release":
        args["is_debug"] = False

    apply_constraints(args)
    return args


def args_to_gn(args: dict) -> str:
    lines = ["# Auto-generated by scripts/build.py. Do not edit."]
    for k in sorted(args):
        v = args[k]
        if isinstance(v, bool):
            lines.append(f"{k} = {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            lines.append(f"{k} = {v}")
        else:
            lines.append(f'{k} = "{v}"')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Build orchestration
# ---------------------------------------------------------------------------

def env_with_depot_tools() -> dict:
    e = os.environ.copy()
    e["PATH"] = f"{DEPOT_TOOLS}{os.pathsep}{e.get('PATH', '')}"
    # Note: do NOT set DEPOT_TOOLS_UPDATE=0 — depot_tools needs to bootstrap
    # its python3_bin_reldir.txt on first use, and that path is gated by the
    # same flag as updates.
    e["DEPOT_TOOLS_WIN_TOOLCHAIN"] = "0"
    return e


def run(cmd, **kw):
    print(f"$ {' '.join(str(c) for c in cmd)}", flush=True)
    # See scripts/setup.py for why Windows needs shell=True with .bat shims.
    if sys.platform == "win32" and isinstance(cmd, list):
        kw.setdefault("shell", True)
        subprocess.check_call(
            subprocess.list2cmdline([str(c) for c in cmd]), **kw)
        return
    subprocess.check_call(cmd, **kw)


def build_v8_path(platform: str, arch: str, config: str,
                  cli_overrides: list[str], package: bool):
    if not (V8_DIR / ".git").is_dir():
        raise SystemExit("[error] third_party/v8 missing — run scripts/setup.py first")

    napi_link = V8_DIR / "napi"
    if not napi_link.is_symlink() and not (napi_link / "BUILD.gn").exists():
        raise SystemExit("[error] v8/napi symlink missing — re-run scripts/setup.py")

    args = compose_args(platform, arch, config, cli_overrides)
    gn_out = f"out/napi-{platform}-{arch}-{config}"
    gn_out_abs = V8_DIR / gn_out
    gn_out_abs.mkdir(parents=True, exist_ok=True)
    (gn_out_abs / "args.gn").write_text(args_to_gn(args))

    env = env_with_depot_tools()
    run(["gn", "gen", gn_out, "--root-target=//napi:default"],
        cwd=str(V8_DIR), env=env)
    run(["ninja", "-C", gn_out, "phony/napi/default",
         "phony/napi/test", "phony/napi/test/test"],
        cwd=str(V8_DIR), env=env)

    # Mirror artifacts to repo's out/build/.
    dist = ROOT / "out" / "build" / f"v8-{platform}-{arch}-{config}"
    dist.mkdir(parents=True, exist_ok=True)
    for name in ("libNapiV8.dylib", "libnapi_v8.so",
                 "napi_v8.dll", "NapiV8.dll"):
        src = gn_out_abs / name
        if src.exists():
            shutil.copy2(src, dist / name)
    for name in ("run", "runner"):
        src = gn_out_abs / name
        if src.exists():
            shutil.copy2(src, dist / name)

    print(f"\n[done] artifacts -> {dist}")
    if package:
        print("[warn] --package not implemented in M1; skipping")


# ---------------------------------------------------------------------------
# Hermes engine path (CMake track)
# ---------------------------------------------------------------------------

def _cmake_build_type(config: str) -> str:
    return "Debug" if config == "debug" else "Release"


# Platforms whose host == target. Cross targets (android, ios) additionally need
# a host-built hermesc/shermes imported into the target Hermes build.
_NATIVE_PLATFORMS = {"linux", "mac", "windows"}
_ANDROID_ABI = {"arm64": "arm64-v8a", "x86_64": "x86_64"}


def _toolchain_file(platform: str) -> Path | None:
    tc = ROOT / "cmake" / "toolchains" / f"{platform}.cmake"
    return tc if tc.exists() else None


def _host_tag() -> tuple[str, str]:
    import platform as _p
    plat = "mac" if sys.platform == "darwin" else "linux"
    arch = "arm64" if _p.machine() in ("arm64", "aarch64") else "x86_64"
    return plat, arch


def _ndk_root() -> Path:
    for v in (os.environ.get("ANDROID_NDK_ROOT"), os.environ.get("ANDROID_NDK_HOME")):
        if v and Path(v).is_dir():
            return Path(v)
    base = Path.home() / "Android/Sdk/ndk"
    if base.is_dir():
        vers = sorted(p for p in base.iterdir() if p.is_dir())
        if vers:
            return vers[-1]
    raise SystemExit("[error] Android NDK not found — set ANDROID_NDK_ROOT")


def _ensure_host_compilers() -> Path:
    """Native build of hermesc+shermes; return its ImportHostCompilers.cmake.

    Cross-compiling Hermes can't run target-built tools, so the baked-in JS is
    compiled by host hermesc/shermes imported via -DIMPORT_HOST_COMPILERS.
    """
    hp, ha = _host_tag()
    hb = ROOT / "out" / "build" / f"hermes-engine-{hp}-{ha}-release"
    if not (hb / "build.ninja").exists():
        run(["cmake", "-S", str(HERMES_DIR), "-B", str(hb), "-G", "Ninja",
             "-DCMAKE_BUILD_TYPE=Release",
             "-DHERMES_ENABLE_TOOLS=ON", "-DHERMES_ENABLE_TEST_SUITE=OFF"])
    run(["cmake", "--build", str(hb), "--target", "hermesc", "shermes"])
    icf = hb / "ImportHostCompilers.cmake"
    if not icf.exists():
        raise SystemExit(f"[error] {icf} not generated by host build")
    return icf


def _strip_so(ndk: Path, so: Path):
    host = "darwin-x86_64" if sys.platform == "darwin" else "linux-x86_64"
    strip = ndk / "toolchains/llvm/prebuilt" / host / "bin" / "llvm-strip"
    if strip.exists() and so.exists():
        run([str(strip), "--strip-unneeded", str(so)])


def build_hermes_path(platform: str, arch: str, config: str, package: bool):
    if not (HERMES_DIR / ".git").is_dir():
        raise SystemExit(
            "[error] third_party/hermes-windows missing — run scripts/setup_hermes.py first")

    build_type = _cmake_build_type(config)
    tag = f"hermes-{platform}-{arch}-{config}"
    hermes_build = ROOT / "out" / "build" / f"hermes-engine-{platform}-{arch}-{config}"
    lib_build = ROOT / "out" / "build" / tag
    ndk = None

    if platform == "android":
        abi = _ANDROID_ABI.get(arch)
        if abi is None:
            raise SystemExit(f"[error] arch '{arch}' unsupported for android")
        ndk = _ndk_root()
        tc = ndk / "build/cmake/android.toolchain.cmake"
        icf = _ensure_host_compilers()
        android_common = [f"-DCMAKE_TOOLCHAIN_FILE={tc}",
                          f"-DANDROID_ABI={abi}", "-DANDROID_PLATFORM=android-21"]
        # No system ICU on Android -> UNICODE_LITE; clang+arm64 elf wants the
        # plain 'gas' boost.context asm (the clang_gas variant is Windows-only);
        # baked-in JS compiled by the host tools.
        hermes_cfg = android_common + [
            f"-DCMAKE_BUILD_TYPE={build_type}",
            "-DHERMES_ENABLE_TOOLS=OFF", "-DHERMES_ENABLE_TEST_SUITE=OFF",
            "-DHERMES_UNICODE_LITE=ON", "-DBOOST_CONTEXT_ASSEMBLER=gas",
            f"-DIMPORT_HOST_COMPILERS={icf}"]
        lib_cfg = android_common + [
            "-DNAPI_ENGINE=hermes", f"-DCMAKE_BUILD_TYPE={build_type}",
            f"-DHERMES_BUILD_DIR={hermes_build}", "-DNAPI_HERMES_BUILD_TESTS=OFF"]
    elif platform in ("ios", "ios_sim"):
        # Same host-hermesc cross mechanism as Android, but with the iOS toolchain
        # (cmake/toolchains/ios.cmake). 'ios' = device sysroot (arm64 only);
        # 'ios_sim' = simulator sysroot (arm64 Apple-silicon / x86_64 Intel).
        icf = _ensure_host_compilers()
        toolchain = _toolchain_file("ios")
        ios_platform = "SIMULATOR" if platform == "ios_sim" else "OS"
        apple_common = [f"-DCMAKE_TOOLCHAIN_FILE={toolchain}",
                        f"-DIOS_PLATFORM={ios_platform}", f"-DIOS_ARCH={arch}"]
        # No system ICU on iOS -> UNICODE_LITE; baked-in JS compiled by the host
        # tools. Apple's compiler id is AppleClang (not Clang), so Boost.Context
        # auto-selects the mach-o 'gas' asm — no BOOST_CONTEXT_ASSEMBLER override.
        hermes_cfg = apple_common + [
            f"-DCMAKE_BUILD_TYPE={build_type}",
            "-DHERMES_ENABLE_TOOLS=OFF", "-DHERMES_ENABLE_TEST_SUITE=OFF",
            "-DHERMES_UNICODE_LITE=ON",
            f"-DIMPORT_HOST_COMPILERS={icf}"]
        lib_cfg = apple_common + [
            "-DNAPI_ENGINE=hermes", f"-DCMAKE_BUILD_TYPE={build_type}",
            f"-DHERMES_BUILD_DIR={hermes_build}", "-DNAPI_HERMES_BUILD_TESTS=OFF"]
    elif platform in _NATIVE_PLATFORMS:
        toolchain = _toolchain_file(platform)
        tc_arg = [f"-DCMAKE_TOOLCHAIN_FILE={toolchain}"] if toolchain else []
        hermes_cfg = tc_arg + [
            f"-DCMAKE_BUILD_TYPE={build_type}",
            "-DHERMES_ENABLE_TOOLS=ON",         # hermesc compiles the baked-in JS
            "-DHERMES_ENABLE_TEST_SUITE=OFF"]
        lib_cfg = tc_arg + [
            "-DNAPI_ENGINE=hermes", f"-DCMAKE_BUILD_TYPE={build_type}",
            f"-DHERMES_BUILD_DIR={hermes_build}"]
    else:
        raise SystemExit(f"[todo] hermes platform '{platform}' not wired (PLAN.md M7.3)")

    # 1) Build the Hermes engine standalone (it must be its own CMake root; it
    #    cannot be add_subdirectory'd). We only need the Node-API + VM archives.
    if not (hermes_build / "build.ninja").exists():
        run(["cmake", "-S", str(HERMES_DIR), "-B", str(hermes_build), "-G", "Ninja",
             *hermes_cfg])
    run(["cmake", "--build", str(hermes_build),
         "--target", "hermesNodeApi", "hermesvm_a"])

    # 2) Build libnapi_hermes against those prebuilt archives.
    run(["cmake", "-S", str(ROOT), "-B", str(lib_build), "-G", "Ninja", *lib_cfg])
    run(["cmake", "--build", str(lib_build)])

    so = lib_build / "src" / "hermes" / "libnapi_hermes.so"
    if platform == "android":
        _strip_so(ndk, so)

    print(f"\n[done] artifacts -> {lib_build / 'src' / 'hermes'}")
    if package:
        from importlib import import_module
        if platform == "android":
            run([sys.executable, str(ROOT / "scripts" / "package_android.py"),
                 "--engine", "hermes", "--config", config])
        else:
            import_module("package_cmake").package(
                engine="hermes", platform=platform, arch=arch, config=config)


# ---------------------------------------------------------------------------
# JSC engine path (CMake track)
# ---------------------------------------------------------------------------
# JSC ships no Node-API, so we hand-write the napi_* surface on JavaScriptCore's
# C API (src/jsc). J1 targets Apple's system JavaScriptCore.framework, so unlike
# the Hermes path there is no engine to pre-build — just configure + build our
# library and the smoke test. Linux/Android/Windows need a built WebKit JSC (J2).

def build_jsc_path(platform: str, arch: str, config: str, package: bool):
    if platform != "mac":
        raise SystemExit(
            f"[todo] jsc only wired for macOS (J1); '{platform}' needs a built "
            "WebKit JavaScriptCore (J2)")
    build_type = "Debug" if config == "debug" else "Release"
    lib_build = ROOT / "out" / "build" / f"jsc-{platform}-{arch}-{config}"
    cfg = ["-DNAPI_ENGINE=jsc", f"-DCMAKE_BUILD_TYPE={build_type}",
           f"-DCMAKE_OSX_ARCHITECTURES={arch}"]
    run(["cmake", "-S", str(ROOT), "-B", str(lib_build), "-G", "Ninja", *cfg])
    run(["cmake", "--build", str(lib_build)])

    dylib = lib_build / "src" / "jsc" / "libnapi_jsc.dylib"
    print(f"\n[done] artifacts -> {lib_build / 'src' / 'jsc'} ({dylib.name})")
    if package:
        raise SystemExit("[todo] jsc packaging (xcframework) is J2")


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", default="v8",
                    choices=["v8", "hermes", "jsc", "quickjs"])
    ap.add_argument("--platform", required=True,
                    choices=["mac", "ios", "ios_sim", "android", "linux", "windows"])
    ap.add_argument("--arch", required=True,
                    choices=["arm64", "x86_64", "x64"])
    ap.add_argument("--config", default="release",
                    choices=["release", "debug"])
    ap.add_argument("--gn-arg", action="append", default=[],
                    metavar="key=value",
                    help="Override a single GN arg; can be repeated")
    ap.add_argument("--package", action="store_true",
                    help="Run platform packaging after build")
    args = ap.parse_args()

    if args.engine == "v8":
        build_v8_path(args.platform, args.arch, args.config,
                      args.gn_arg, args.package)
    elif args.engine == "hermes":
        build_hermes_path(args.platform, args.arch, args.config, args.package)
    elif args.engine == "jsc":
        build_jsc_path(args.platform, args.arch, args.config, args.package)
    else:
        raise SystemExit(f"[todo] engine {args.engine} not yet supported")


if __name__ == "__main__":
    main()
