#!/usr/bin/env python3
"""Build entrypoint for napi-impl.

V8 engine path (this script's focus):
  1. Load config/v8_args.yml (+ optional v8_args.local.yml, $NAPI_GN_EXTRA_ARGS_FILE, --gn-arg).
  2. Apply constraint expansion (jitless bundle).
  3. Write args.gn into V8's out dir.
  4. Run `gn gen` and `ninja` from the V8 source tree.
  5. Copy artifacts to out/build/<engine>-<platform>-<arch>-<config>/.

CMake engine paths (hermes/jsc/quickjs): TODO M7.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    sys.stderr.write("Missing PyYAML. Install with: pip3 install pyyaml\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
THIRD_PARTY = ROOT / "third_party"
V8_DIR = THIRD_PARTY / "v8"
DEPOT_TOOLS = THIRD_PARTY / "depot_tools"


# ---------------------------------------------------------------------------
# YAML loading & merging
# ---------------------------------------------------------------------------

def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def _deep_merge(dst: dict, src: dict) -> dict:
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            _deep_merge(dst[k], v)
        else:
            dst[k] = v
    return dst


def _parse_gn_value(s: str):
    sl = s.lower()
    if sl in ("true", "false"):
        return sl == "true"
    try:
        return int(s)
    except ValueError:
        pass
    return s  # treat as string


# Constraints: when key=value matches, force the listed peers.
# 注：pointer compression 不在此 bundle——它与 jitless 正交（jitless 关 JIT，pointer
# compression 只改堆内指针布局），由各平台自选（移动端开启以省堆内存）。sandbox 仍强制
# 关闭：jitless 平台同样走跨 C ABI 的 user-malloc backing store，sandbox 会限制它。
JITLESS_BUNDLE = {
    "v8_enable_webassembly": False,
    "v8_enable_sandbox": False,
    "v8_enable_maglev": False,
    "v8_enable_turbofan": False,
}


def apply_constraints(args: dict) -> dict:
    if args.get("v8_jitless") is True:
        for k, v in JITLESS_BUNDLE.items():
            if k in args and args[k] != v:
                raise SystemExit(
                    f"[constraint] v8_jitless=true forces {k}={v}, "
                    f"but user set {k}={args[k]}"
                )
            args[k] = v
    return args


def compose_args(platform: str, arch: str, config: str,
                 cli_overrides: list[str]) -> dict:
    key = f"{platform}_{arch}"
    defaults = _load_yaml(ROOT / "config" / "v8_args.yml")

    args = dict(defaults.get("common", {}))
    plat_block = defaults.get("platforms", {}).get(key)
    if plat_block is None:
        raise SystemExit(f"[error] platforms.{key} not defined in v8_args.yml")
    args.update(plat_block)

    local = _load_yaml(ROOT / "config" / "v8_args.local.yml")
    _deep_merge(args, local.get("common", {}))
    _deep_merge(args, local.get("platforms", {}).get(key, {}))

    extra_path = os.environ.get("NAPI_GN_EXTRA_ARGS_FILE")
    if extra_path:
        _deep_merge(args, _load_yaml(Path(extra_path)))

    for kv in cli_overrides:
        if "=" not in kv:
            raise SystemExit(f"[error] --gn-arg expects key=value, got: {kv}")
        k, v = kv.split("=", 1)
        args[k.strip()] = _parse_gn_value(v.strip())

    if config == "debug":
        # common 的 symbol_level=0 是 release 减包默认(A1)；debug 覆盖回完整符号。
        # 直接赋值(非 setdefault)，因 common 已把 symbol_level 设为 release 默认 0。
        args["is_debug"] = True
        args["symbol_level"] = 2
    elif config == "release":
        args["is_debug"] = False

    apply_constraints(args)
    return args


def args_to_gn(args: dict) -> str:
    lines = ["# Auto-generated by scripts/build.py. Do not edit."]
    for k in sorted(args):
        v = args[k]
        if isinstance(v, bool):
            lines.append(f"{k} = {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            lines.append(f"{k} = {v}")
        else:
            lines.append(f'{k} = "{v}"')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Build orchestration
# ---------------------------------------------------------------------------

def env_with_depot_tools() -> dict:
    e = os.environ.copy()
    e["PATH"] = f"{DEPOT_TOOLS}{os.pathsep}{e.get('PATH', '')}"
    # Note: do NOT set DEPOT_TOOLS_UPDATE=0 — depot_tools needs to bootstrap
    # its python3_bin_reldir.txt on first use, and that path is gated by the
    # same flag as updates.
    e["DEPOT_TOOLS_WIN_TOOLCHAIN"] = "0"
    return e


def run(cmd, **kw):
    print(f"$ {' '.join(str(c) for c in cmd)}", flush=True)
    # See scripts/setup.py for why Windows needs shell=True with .bat shims.
    if sys.platform == "win32" and isinstance(cmd, list):
        kw.setdefault("shell", True)
        subprocess.check_call(
            subprocess.list2cmdline([str(c) for c in cmd]), **kw)
        return
    subprocess.check_call(cmd, **kw)


def build_v8_path(platform: str, arch: str, config: str,
                  cli_overrides: list[str], package: bool):
    if not (V8_DIR / ".git").is_dir():
        raise SystemExit("[error] third_party/v8 missing — run scripts/setup.py first")

    napi_link = V8_DIR / "napi"
    if not napi_link.is_symlink() and not (napi_link / "BUILD.gn").exists():
        raise SystemExit("[error] v8/napi symlink missing — re-run scripts/setup.py")

    args = compose_args(platform, arch, config, cli_overrides)
    gn_out = f"out/napi-{platform}-{arch}-{config}"
    gn_out_abs = V8_DIR / gn_out
    gn_out_abs.mkdir(parents=True, exist_ok=True)
    (gn_out_abs / "args.gn").write_text(args_to_gn(args))

    env = env_with_depot_tools()
    run(["gn", "gen", gn_out, "--root-target=//napi:default"],
        cwd=str(V8_DIR), env=env)
    run(["ninja", "-C", gn_out, "phony/napi/default",
         "phony/napi/test", "phony/napi/test/test"],
        cwd=str(V8_DIR), env=env)

    # Mirror artifacts to repo's out/build/.
    dist = ROOT / "out" / "build" / f"v8-{platform}-{arch}-{config}"
    dist.mkdir(parents=True, exist_ok=True)
    for name in ("libNapiV8.dylib", "libnapi_v8.so",
                 "napi_v8.dll", "NapiV8.dll"):
        src = gn_out_abs / name
        if src.exists():
            shutil.copy2(src, dist / name)
    for name in ("run", "runner"):
        src = gn_out_abs / name
        if src.exists():
            shutil.copy2(src, dist / name)

    print(f"\n[done] artifacts -> {dist}")
    if package:
        print("[warn] --package not implemented in M1; skipping")


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", default="v8",
                    choices=["v8", "hermes", "jsc", "quickjs"])
    ap.add_argument("--platform", required=True,
                    choices=["mac", "ios", "ios_sim", "android", "linux", "windows"])
    ap.add_argument("--arch", required=True,
                    choices=["arm64", "x86_64", "x64"])
    ap.add_argument("--config", default="release",
                    choices=["release", "debug"])
    ap.add_argument("--gn-arg", action="append", default=[],
                    metavar="key=value",
                    help="Override a single GN arg; can be repeated")
    ap.add_argument("--package", action="store_true",
                    help="Run platform packaging after build")
    args = ap.parse_args()

    if args.engine == "v8":
        build_v8_path(args.platform, args.arch, args.config,
                      args.gn_arg, args.package)
    else:
        raise SystemExit(f"[todo] engine {args.engine} not yet supported (M7)")


if __name__ == "__main__":
    main()
