#!/usr/bin/env python3
"""Build a CMake-consumable napi package for one engine/platform/arch.

Layout produced (engine = v8 | hermes):
  out/dist/napi-<engine>-<platform>-<arch>/
  ├── include/
  │   ├── napi/...        (synced upstream Node-API headers)
  │   └── napi_v8/...     (embedding API; v8 also ships inspector + sab)
  ├── lib/                (libnapi_<engine>.{so,dylib} / napi_<engine>.dll+.lib)
  ├── cmake/
  │   ├── napi_<engine>-config.cmake
  │   └── napi_<engine>-config-version.cmake
  └── BUILD_INFO.md

Consumers: `find_package(napi_<engine> REQUIRED CONFIG)` →
           `target_link_libraries(myapp PRIVATE napi_<engine>::napi_<engine>)`.

Bundled artifact written next to the directory (.zip on Windows, .tar.gz else).
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "out" / "dist"

CONFIG_TMPL = """\
# Generated by scripts/package_cmake.py
if(TARGET {base}::{base})
  return()
endif()

get_filename_component(_{base}_root "${{CMAKE_CURRENT_LIST_DIR}}/.." ABSOLUTE)

add_library({base}::{base} SHARED IMPORTED)
set_target_properties({base}::{base} PROPERTIES
  IMPORTED_LOCATION "${{_{base}_root}}/lib/{lib_runtime}"
  INTERFACE_INCLUDE_DIRECTORIES "${{_{base}_root}}/include"{import_lib}
)

set({base}_VERSION {version})
set({base}_INCLUDE_DIR "${{_{base}_root}}/include")
set({base}_LIBRARY "${{_{base}_root}}/lib/{lib_runtime}")
"""

VERSION_TMPL = """\
set(PACKAGE_VERSION "{version}")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
"""

# Per-engine, per-platform runtime / import-lib file naming.
PLATFORM_LIB = {
    "v8": {
        "linux":   ("libnapi_v8.so",   None),
        "android": ("libnapi_v8.so",   None),
        "mac":     ("libNapiV8.dylib", None),
        "ios":     ("libNapiV8.dylib", None),
        "ios_sim": ("libNapiV8.dylib", None),
        "windows": ("napi_v8.dll",     "napi_v8.lib"),
    },
    "hermes": {
        "linux":   ("libnapi_hermes.so",    None),
        "android": ("libnapi_hermes.so",    None),
        "mac":     ("libnapi_hermes.dylib", None),
        "ios":     ("libnapi_hermes.dylib", None),
        "windows": ("napi_hermes.dll",      "napi_hermes.lib"),
    },
}


def _src_build(engine: str, platform: str, arch: str, config: str) -> Path:
    base = ROOT / "out" / "build"
    if engine == "hermes":
        # libnapi_hermes lands in the CMake target's subdir.
        return base / f"hermes-{platform}-{arch}-{config}" / "src" / "hermes"
    return base / f"v8-{platform}-{arch}-{config}"


def package(engine: str, platform: str, arch: str, config: str = "release",
            version: str = "1.0.0") -> Path:
    base = f"napi_{engine}"
    runtime, import_lib = PLATFORM_LIB[engine][platform]

    src_build = _src_build(engine, platform, arch, config)
    if not (src_build / runtime).exists():
        sys.exit(f"[error] {src_build / runtime} missing; run build.py first")

    pkg_name = f"napi-{engine}-{platform}-{arch}"
    pkg = DIST / pkg_name
    if pkg.exists():
        shutil.rmtree(pkg)
    (pkg / "include").mkdir(parents=True)
    (pkg / "lib").mkdir()
    (pkg / "cmake").mkdir()

    # Headers: the standard napi/ surface always; the embedding header for both
    # engines. The v8-only inspector + sab headers ship only with the v8 build.
    shutil.copytree(ROOT / "include" / "napi", pkg / "include" / "napi",
                    dirs_exist_ok=True)
    (pkg / "include" / "napi_v8").mkdir(exist_ok=True)
    if engine == "v8":
        shutil.copytree(ROOT / "include" / "napi_v8", pkg / "include" / "napi_v8",
                        dirs_exist_ok=True)
    else:
        shutil.copy2(ROOT / "include" / "napi_v8" / "embedding.h",
                     pkg / "include" / "napi_v8" / "embedding.h")

    # Libraries
    shutil.copy2(src_build / runtime, pkg / "lib" / runtime)
    import_lib_prop = ""
    if import_lib:
        impsrc = src_build / import_lib
        if impsrc.exists():
            shutil.copy2(impsrc, pkg / "lib" / import_lib)
        import_lib_prop = (
            f'\n  IMPORTED_IMPLIB "${{_{base}_root}}/lib/{import_lib}"')

    (pkg / "cmake" / f"{base}-config.cmake").write_text(
        CONFIG_TMPL.format(base=base, lib_runtime=runtime,
                           import_lib=import_lib_prop, version=version))
    (pkg / "cmake" / f"{base}-config-version.cmake").write_text(
        VERSION_TMPL.format(version=version))

    info = ROOT / "scripts" / "gen_build_info.py"
    if info.exists():
        subprocess.check_call([
            sys.executable, str(info),
            "--platforms", f"{platform}/{arch}",
            "--version", version,
            "--out", str(pkg / "BUILD_INFO.md")])

    # Bundle
    if platform == "windows":
        out_arc = DIST / f"{pkg_name}.zip"
        if out_arc.exists():
            out_arc.unlink()
        with zipfile.ZipFile(out_arc, "w", zipfile.ZIP_DEFLATED) as zf:
            for p in pkg.rglob("*"):
                if p.is_file():
                    zf.write(p, p.relative_to(pkg.parent))
    else:
        out_arc = DIST / f"{pkg_name}.tar.gz"
        if out_arc.exists():
            out_arc.unlink()
        with tarfile.open(out_arc, "w:gz") as tf:
            tf.add(pkg, arcname=pkg.name)

    print(f"[done] {out_arc}")
    print(f"  size: {out_arc.stat().st_size / 1024 / 1024:.1f} MB")
    return out_arc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", default="v8", choices=["v8", "hermes"])
    ap.add_argument("--platform", required=True)
    ap.add_argument("--arch", required=True)
    ap.add_argument("--config", default="release")
    ap.add_argument("--version", default="1.0.0")
    args = ap.parse_args()
    if args.platform not in PLATFORM_LIB[args.engine]:
        sys.exit(f"[error] platform {args.platform} not supported for {args.engine}")
    package(args.engine, args.platform, args.arch, args.config, args.version)


if __name__ == "__main__":
    main()
