#!/usr/bin/env python3
"""Build a CMake-consumable napi_v8 package for Linux/Windows.

Layout produced:
  out/dist/napi-v8-<platform>-<arch>/
  ├── include/
  │   ├── napi/...      (synced upstream Node-API headers)
  │   └── napi_v8/...   (our embedding + inspector)
  ├── lib/
  │   ├── libnapi_v8.so  (Linux)
  │   └── napi_v8.dll + napi_v8.lib (Windows)
  └── cmake/
      ├── napi_v8-config.cmake
      └── napi_v8-config-version.cmake

Consumers: `find_package(napi_v8 REQUIRED CONFIG)` →
           `target_link_libraries(myapp PRIVATE napi_v8::napi_v8)`.
"""
from __future__ import annotations

import argparse
import shutil
import sys
import tarfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "out" / "dist"

CONFIG_TMPL = """\
# Generated by scripts/package_cmake.py
if(TARGET napi_v8::napi_v8)
  return()
endif()

get_filename_component(_napi_v8_root "${{CMAKE_CURRENT_LIST_DIR}}/.." ABSOLUTE)

add_library(napi_v8::napi_v8 SHARED IMPORTED)
set_target_properties(napi_v8::napi_v8 PROPERTIES
  IMPORTED_LOCATION "${{_napi_v8_root}}/lib/{lib_runtime}"
  INTERFACE_INCLUDE_DIRECTORIES "${{_napi_v8_root}}/include"
{import_lib})

set(napi_v8_VERSION {version})
set(napi_v8_INCLUDE_DIR "${{_napi_v8_root}}/include")
set(napi_v8_LIBRARY "${{_napi_v8_root}}/lib/{lib_runtime}")
"""

VERSION_TMPL = """\
set(PACKAGE_VERSION "{version}")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--platform", required=True,
                    choices=["linux", "windows"])
    ap.add_argument("--arch", default="x64")
    ap.add_argument("--config", default="release")
    ap.add_argument("--version", default="1.0.0")
    args = ap.parse_args()

    src_build = ROOT / "out" / "build" / f"v8-{args.platform}-{args.arch}-{args.config}"
    if not src_build.is_dir():
        sys.exit(f"[error] {src_build} missing; run build.py first")

    pkg = DIST / f"napi-v8-{args.platform}-{args.arch}"
    if pkg.exists():
        shutil.rmtree(pkg)
    (pkg / "include").mkdir(parents=True)
    (pkg / "lib").mkdir()
    (pkg / "cmake").mkdir()

    # Headers
    for src in (ROOT / "include" / "napi", ROOT / "include" / "napi_v8"):
        shutil.copytree(src, pkg / "include" / src.name, dirs_exist_ok=True)

    # Libraries
    import_lib_prop = ""
    if args.platform == "linux":
        runtime = "libnapi_v8.so"
        shutil.copy2(src_build / runtime, pkg / "lib" / runtime)
    else:  # windows
        runtime = "napi_v8.dll"
        import_lib = "napi_v8.lib"
        shutil.copy2(src_build / runtime, pkg / "lib" / runtime)
        if (src_build / import_lib).exists():
            shutil.copy2(src_build / import_lib, pkg / "lib" / import_lib)
        import_lib_prop = (
            f'  IMPORTED_IMPLIB "${{_napi_v8_root}}/lib/{import_lib}"\n)')

    (pkg / "cmake" / "napi_v8-config.cmake").write_text(
        CONFIG_TMPL.format(lib_runtime=runtime,
                           import_lib=import_lib_prop,
                           version=args.version))
    (pkg / "cmake" / "napi_v8-config-version.cmake").write_text(
        VERSION_TMPL.format(version=args.version))

    # BUILD_INFO.md at package root.
    import subprocess as _sp
    _sp.check_call([
        sys.executable, str(ROOT / "scripts" / "gen_build_info.py"),
        "--platforms", f"{args.platform}/{args.arch}",
        "--version", args.version,
        "--out", str(pkg / "BUILD_INFO.md")])

    # Bundle tarball / zip
    if args.platform == "linux":
        out_tar = DIST / f"napi-v8-{args.platform}-{args.arch}.tar.gz"
        if out_tar.exists(): out_tar.unlink()
        with tarfile.open(out_tar, "w:gz") as tf:
            tf.add(pkg, arcname=pkg.name)
        artifact = out_tar
    else:
        out_zip = DIST / f"napi-v8-{args.platform}-{args.arch}.zip"
        if out_zip.exists(): out_zip.unlink()
        with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
            for p in pkg.rglob("*"):
                if p.is_file():
                    zf.write(p, p.relative_to(pkg.parent))
        artifact = out_zip

    print(f"[done] {artifact}")
    print(f"  size: {artifact.stat().st_size / 1024 / 1024:.1f} MB")


if __name__ == "__main__":
    main()
